Repository hmcts/pip-cron-trigger, pull requests merged in 2023-07, with the labels that each got.

#96 Suppress CVE-2023-34462
  config/owasp/suppressions.xml
Labels: ns:pip, prd:pip, rel:pip-cron-trigger-pr-96

#94 PUB-1687 - Upgraded spring
  .github/workflows/ci.yml
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:pip, prd:pip, rel:pip-cron-trigger-pr-94

#106 Updated vulnerability
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:pip, prd:pip, rel:pip-cron-trigger-pr-106
